### ISSUE TITLE
ValueError: Empty dictionary was passed as an input!

### ISSUE THREAD

**Issue by puzhongji-CADEE** [labstructbioinf/rossmann-toolbox#13]
## Issue Description
After successfully running `example_minimal.ipynb`, I encountered a `ValueError` when attempting to predict with a valid input dictionary using `RossmannToolbox`. Despite providing a non-empty dictionary, the error `Empty dictionary was passed as an input!` is raised.

## Steps to Reproduce
1. Ensure that `example_minimal.ipynb` runs without issues.
2. Install RossmannToolbox with GPU support.
3. Execute the following code snippet:

```python
import matplotlib.pylab as plt
from rossmann_toolbox import RossmannToolbox
rtb = RossmannToolbox(use_gpu=True)

# Example 1
# The b-a-b core is predicted in the full-length sequence

data = {'8C6A_A': 'RSTLVHWFRKGLRLHDNPALSHIFTAANAAPGRYFVRPIFILDPGILDWMQVGANRWRFLQQTLEDLDNQLRKLNSRLFVVRGKPAEVFPRIFKSWRVEMLTFETDIEPYSVTRDAAVQKLAKAEGVRVETHCSHTIYNPELVIAKNLGKAPITYQKFLGIVEQLKVPKVLGVPEKLKNMPTPPKDEVEQKDSAAYDCPTMKQLVKRPEELGPNKFPGGETEALRRMEESLKDEIWVARFEKPNTAPNSLEPSTTVLSPYLKFGCLSARLFNQKLKEIIKRQPKHSQPPVSLIGQLMWREFYYTVAAAEPNFDRMLGNVYCMQIPWQEHPDHLEAWTHGRTGYPFIDAIMRQLRQEGWIHHLARHAVACFLTRGDLWISWEEGQRVFEQLLLDQDWALNAGNWMWLSASAFFHQYFRVYSPVAFGKKTDPQGHYIRKYVPELSKYPAGCIYEPWKASLVDQRAYGCVLGTDYPHRIVKHEVVHKENIKRMGAAYKVNREV'}

preds = rtb.predict(data, mode='seq', core_detect_mode='dl', importance=False)
print(preds)

**Comment by staszekdh** [comment]
The problem is due to the beta-alpha-beta (b-a-b) cofactor binding motif not being recognized in the full-length input sequence. Since all such cases are silently removed from an input dictionary, this resulted in an empty dictionary in your case and thus the `ValueError: Empty dictionary`. (@Argusmocny it would be nice to handle this somehow).

There are two options for b-a-b motif detection, `core_detect_mode='dl'` and `core_detect_mode='hhsearch'`. The former does not seem to work with your sequence, so you can try the latter (which requires a path to hhsearch):

```
PATH_HHPRED = '/opt/apps/hh-suite/bin/hhsearch'.

rtb = RossmannToolbox(use_gpu=True, hhsearch_loc = PATH_HHPRED)
```

Alternatively, you can define the b-a-b regions manually and pass them as input with `mode='core'`.

p.s. Also note that your protein belongs to the HUP family, which is very distantly related to the Rossmann family (https://pubmed.ncbi.nlm.nih.gov/34384295/).
